export const swaggerDocument = {
  openapi: '3.0.3',
  info: {
    title: 'AiBus High-Scale Bus Booking API',
    version: '1.0.0',
    description:
      'Production-grade Bus Booking Backend capable of supporting millions of users, high concurrency, large booking volumes, unreliable upstream third-party GDS providers, distributed locking, payment failures, and automated reconciliation.',
    contact: {
      name: 'Engineering Team',
      email: 'engineering@aibus.internal',
    },
  },
  servers: [
    {
      url: 'http://localhost:3000',
      description: 'Local development server',
    },
  ],
  components: {
    securitySchemes: {
      BearerAuth: {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
        description: 'Provide your JWT access token generated by the /api/v1/auth/login endpoint',
      },
      IdempotencyHeader: {
        type: 'apiKey',
        in: 'header',
        name: 'Idempotency-Key',
        description: 'UUIDv4 key to prevent duplicate mutating transactions',
      },
    },
    schemas: {
      ApiResponse: {
        type: 'object',
        properties: {
          success: { type: 'boolean' },
          data: { type: 'object' },
          message: { type: 'string' },
          meta: { type: 'object' },
        },
      },
      ApiError: {
        type: 'object',
        properties: {
          success: { type: 'boolean', example: false },
          error: {
            type: 'object',
            properties: {
              code: { type: 'string' },
              message: { type: 'string' },
              details: { type: 'array', items: { type: 'object' } },
            },
          },
        },
      },
    },
  },
  paths: {
    '/health/live': {
      get: {
        summary: 'Liveness Probe',
        description: 'Verifies the Node.js process is active and accepting requests (used by Kubernetes liveness probes).',
        responses: {
          '200': { description: 'Process alive' },
        },
      },
    },
    '/health/ready': {
      get: {
        summary: 'Readiness Probe',
        description: 'Verifies external dependencies (PostgreSQL, Redis) are reachable before receiving production traffic.',
        responses: {
          '200': { description: 'Dependencies healthy' },
          '503': { description: 'One or more dependencies failing' },
        },
      },
    },
    '/api/v1/auth/register': {
      post: {
        summary: 'User Registration',
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                type: 'object',
                required: ['email', 'password', 'firstName', 'lastName'],
                properties: {
                  email: { type: 'string', format: 'email' },
                  password: { type: 'string', minLength: 8 },
                  firstName: { type: 'string' },
                  lastName: { type: 'string' },
                  phone: { type: 'string' },
                },
              },
            },
          },
        },
        responses: {
          '201': { description: 'User successfully registered with token pair' },
          '409': { description: 'Email already registered' },
        },
      },
    },
    '/api/v1/auth/login': {
      post: {
        summary: 'User Login',
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                type: 'object',
                required: ['email', 'password'],
                properties: {
                  email: { type: 'string' },
                  password: { type: 'string' },
                },
              },
            },
          },
        },
        responses: {
          '200': { description: 'Authenticated successfully' },
          '401': { description: 'Invalid email or password' },
        },
      },
    },
    '/api/v1/search': {
      get: {
        summary: 'Search Buses',
        description: 'Searches buses between cities for a given journey date with multi-layer Redis caching (5 min TTL) and upstream GDS fallback.',
        parameters: [
          { name: 'fromCityId', in: 'query', required: true, schema: { type: 'integer' } },
          { name: 'toCityId', in: 'query', required: true, schema: { type: 'integer' } },
          { name: 'journeyDate', in: 'query', required: true, schema: { type: 'string', format: 'date' } },
          { name: 'isAC', in: 'query', schema: { type: 'boolean' } },
          { name: 'isSleeper', in: 'query', schema: { type: 'boolean' } },
          { name: 'sortBy', in: 'query', schema: { type: 'string', enum: ['fare_asc', 'fare_desc', 'departure_asc', 'departure_desc'] } },
        ],
        responses: {
          '200': { description: 'List of matching bus schedules' },
          '400': { description: 'Missing required query parameters' },
        },
      },
    },
    '/api/v1/buses/{busId}/chart': {
      get: {
        summary: 'Seat Layout Chart',
        description: 'Fetches seat deck layouts, pricing, seat availability, and male/female reservation quotas.',
        parameters: [{ name: 'busId', in: 'path', required: true, schema: { type: 'integer' } }],
        responses: {
          '200': { description: 'Seat layout, deck breakdown, and boarding/dropping points' },
        },
      },
    },
    '/api/v1/holds': {
      post: {
        summary: 'Hold Seats (Multi-Layer Distributed Lock)',
        description: 'Acquires 30s Redis distributed locks, invokes upstream GDS HoldSeats, persists hold with 10-minute TTL, and schedules BullMQ expiry cleanup.',
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                type: 'object',
                required: ['fromCityId', 'toCityId', 'journeyDate', 'busId', 'pickupId', 'dropoffId', 'contactInfo', 'passengers'],
                properties: {
                  fromCityId: { type: 'integer' },
                  toCityId: { type: 'integer' },
                  journeyDate: { type: 'string' },
                  busId: { type: 'integer' },
                  pickupId: { type: 'string' },
                  dropoffId: { type: 'string' },
                  passengers: {
                    type: 'array',
                    items: {
                      type: 'object',
                      properties: {
                        seatNo: { type: 'string' },
                        seatTypeId: { type: 'integer' },
                        fare: { type: 'number' },
                        gender: { type: 'string', enum: ['M', 'F'] },
                        age: { type: 'integer' },
                        name: { type: 'string' },
                      },
                    },
                  },
                },
              },
            },
          },
        },
        responses: {
          '201': { description: 'Seats held successfully' },
          '409': { description: 'Seat already locked or held by another user' },
        },
      },
    },
    '/api/v1/bookings': {
      post: {
        summary: 'Create Booking',
        description: 'Creates a booking record linked to an active hold.',
        responses: {
          '201': { description: 'Booking created with status HELD' },
        },
      },
    },
    '/api/v1/payments/intent': {
      post: {
        summary: 'Create Payment Intent',
        description: 'Generates merchant transaction ID and initiates payment gateway intent (protected by Idempotency-Key).',
        responses: {
          '201': { description: 'Payment intent created with checkout redirect URL' },
        },
      },
    },
    '/api/v1/payments/verify': {
      post: {
        summary: 'Verify Payment & Confirm Booking',
        description: 'Verifies payment status and calls GDS BookSeats. If GDS times out, transitions booking to BOOKING_UNKNOWN and queues automatic background reconciliation.',
        responses: {
          '200': { description: 'Booking confirmed and ticket issued' },
          '400': { description: 'Payment verification failed' },
        },
      },
    },
    '/api/v1/tickets/booking/{bookingId}': {
      get: {
        summary: 'Get Digital Ticket',
        description: 'Fetches digital travel itinerary, PNR number, ticket number, passenger list, and boarding snapshot.',
        parameters: [{ name: 'bookingId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        responses: {
          '200': { description: 'Ticket found' },
          '404': { description: 'Ticket not found' },
        },
      },
    },
    '/api/v1/cancellations/{bookingId}/check': {
      get: {
        summary: 'Check Cancellability',
        description: 'Calculates refund percentage, cancellation fee, and projected refund amount according to operator cancellation policy.',
        parameters: [{ name: 'bookingId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        responses: {
          '200': { description: 'Cancellability status and refund projection' },
        },
      },
    },
    '/api/v1/cancellations/{bookingId}': {
      post: {
        summary: 'Cancel Seats',
        description: 'Cancels seats with upstream GDS provider, transitions booking to CANCELLED, and enqueues refund on BullMQ refund queue.',
        parameters: [{ name: 'bookingId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        responses: {
          '200': { description: 'Cancellation completed and refund queued' },
        },
      },
    },
  },
};
